spotify-recommendations/spotify_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "spotify_app"

urlpatterns = [
    path("playlists/", views.PlaylistListFormView.as_view(), name="playlist_list"),
    path("playlists/<playlist_id>", views.ChosenPlaylistListView.as_view(), name="playlist_detail"),
    path("playlists/<playlist_id>/recommend", views.RecommendationsView.as_view(), name="recommendations"),
]

spotify-recommendations/spotify_recs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("", include("spotify_app.urls", namespace="spotify_app")),
    path("social/", include("social_django.urls")),
    path("", include("django.contrib.auth.urls")),
]

spotify-recommendations/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Spotify Recommendation System</title>
    <!-- Latest compiled and minified CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/css/load-button.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <script src="{% static '/js/button-load.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-light" role='navigation' id='navbar'>
    <div class="container">
        <a href="{% if user.is_authenticated %}{% url 'spotify_app:playlist_list' %} {% else %} {% url 'home' %} {% endif %}"
           class="navbar-brand nav-link fas fa-home fa-2x" id='homeButton'><i></i></a>
        <button class="navbar-toggler navbar-toggle" type="button" data-toggle="collapse"
                data-target="#collapsibleNavbar" id="hamburger"><i class="fas fa-bars hamburger"></i>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav ">
                <li class='nav-item nav-text'>
                </li>
                <li class="nav-item nav-text">
                </li>
                <li class='nav-item nav-text' id=>
                <li class='nav-item'>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="header-link"><i
                                class="nav-link fas fa-sign-out-alt fa-2x"></i></a>
                    {% else %}
                        <a href="{% url "social:begin" "spotify" %}"><i
                                class="nav-link fas fa-sign-in-alt fa-2x"></i></a>
                    {% endif %}
                </li>
                <li class='nav-item'><a href="https://github.com/ShapeAI">
                    <i id="navGithubBtn" class="nav-link fab fa-github fa-2x"></i></a>
                </li>
                <li class='nav-item'><a href="https://www.linkedin.com/company/shapeai/">
                    <i id="navLinkedInBtn" class=" nav-link fab fa-linkedin fa-2x"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
<div class="globalContainer container-fluid">
    <section class="row myContent">
        {% block content %}
            <p></p>
        {% endblock content %}
    </section>
</html>

spotify-recommendations/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12" style="font-family: 'Roboto', sans-serif;">
                    <div class="jumbotron custom-jumbo">
                        <h1 class="text-primary display-4"> Spotify Song Recommender</h1>
                        <h3 class="display-3 recommendations-greeting" style='font-size:70px;';>Hi {{ first_name }} ! &#128578; </h3>
                        <div class="row">
                            <div class="col-md-6">
                                <p class="text">Choose a playlist you'd like to get recommendations from!</p>
                                <p class="text">Simply click on a playlist to get a recommendation from its tracks that
                                    you'll like the most</p>
                                <p class="text">Here is a list of <span class="text-success font-weight-bold" style="font-family: 'Roboto', sans-serif; letter-spacing: 3px;">Spotify's featured playlists</span> right now in real time:</p>
                                {% for pb in playlist_batches %}
                                    <div class="container playlist-thumb-container">
                                        <div class="row justify-content-md-around">
                                            {% if pb.0.playlist_featured %}
                                                <div class="col-lg-4">
                                                    <div class="card playlist-thumb playlist-thumb-left">
                                                        <a class="card"
                                                           href="{% url "spotify_app:playlist_detail" pb.0.playlist_id %}">
                                                            <img class="img-responsive"
                                                                 src="{{ pb.0.playlist_img_src }}">
                                                        </a>
                                                    </div>
                                                </div>
                                            {% endif %}
                                            {% if pb.1.playlist_featured %}
                                                <div class="col-lg-4">
                                                    <div class="card playlist-thumb playlist-thumb-right">
                                                        <a class="card"
                                                           href="{% url "spotify_app:playlist_detail" pb.1.playlist_id %}">
                                                            <img class="img-responsive"
                                                                 src="{{ pb.1.playlist_img_src }}">
                                                        </a>
                                                    </div>
                                                </div>
                                            {% endif %}
                                            {% if pb.2.playlist_featured %}
                                                <div class="col-lg-4">
                                                    <div class="card playlist-thumb playlist-thumb-right">
                                                        <a class="card"
                                                           href="{% url "spotify_app:playlist_detail" pb.2.playlist_id %}">
                                                            <img class="img-responsive"
                                                                 src="{{ pb.2.playlist_img_src }}">
                                                        </a>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-6">
                                <p class="text">Or you can use a playlist of your own choosing!</p>
                                <p class="text">Go to your Spotify, right click on the three dots, then share, and "Copy
                                    Spotify URI"</p>
                                <form method="post" class="text custom-playlist-form">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" value="Take me to the Playlist!!"
                                           class="btn btn-success btn custom-playlist-button">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container-fluid">
                <div class="col-lg-12 login-container">
                    <div class="jumbotron">
                        <h1 styles="font-weight-bold" class="login-rec display-4">Spotify Song Recommender</h1> 
                        <p class="login-lead">Please log in to your Spotify account to get song recommendations.</p>
                        <p class="lead">
                            <a class="btn btn-success btn-lg" href="{% url "social:begin" "spotify" %}"
                               role="button">Log in with Spotify</a>
                        </p>
                    </div>
                </div>
        </div>
    {% endif %}
{% endblock content %}

spotify-recommendations/templates/recommendations.html
{% extends "base.html" %}
{% load static %}


{% block content %}


    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 rec-main-col">
                    <div class="jumbotron">
                        <h1 class="display-4 recommendations-title">Spotify Song Recommender</h1>
                        <div class="row">
                            <div class="col-md-6">

                                <iframe class="embedded-playlist"
                                        src="https://open.spotify.com/embed/playlist/{{ chosen_playlist.playlist_id }}"
                                        width="500" height="1000"
                                        frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
                            </div>
                            <div class="col-md-6">
                                <div class="container-fluid">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                {% if not script_ran and not remove_rec_button %}
                                                    <div class="recommendation-text ">
                                                        <p class="text">By clicking the button below, we will provide
                                                            you with the song
                                                            recommendations from the
                                                            playlist you selected by pulling in all of the songs you
                                                            have
                                                            saved, and
                                                            the contents of all playlists you have created on
                                                            Spotify.</p>

                                                        <p class="text">Depending on the amount of songs/playlists you
                                                            have
                                                            saved/created, this can take quite some time to run the
                                                            first time
                                                            you get recommendations because we have to analyze your
                                                            library.
                                                            Please be patient, and be aware that if you do not have much
                                                            saved content, you may not get recommendations.</p>
                                                    </div>
                                                    <div class="col-xs-12 button-holder">
                                                    <div class="ajax-button">
                                                        <div class="fa fa-check done"></div>
                                                        <div class="fa fa-close failed"></div>
                                                        <a href="
                                        {% url "spotify_app:recommendations" chosen_playlist.playlist_id %}">
                                                            <input id="submit" class="submit rec-button" type="button"
                                                                   value="Give me recommendations"/></a>
                                                    </div>
                                                {% elif script_ran %}
                                                    <div class="recommendation-text">
                                                        <p class="text">All done! Below are your recommendations from
                                                            the playlist on
                                                            the
                                                            left. Click on any of the buttons
                                                            to be redirected to Spotify's website to listen to the
                                                            song!</p>
                                                    </div>
                                                    <div class="recommendations-for-blank"><h2>Song recommendations
                                                        for {{ first_name }}:</h2></div>
                                                    {% for rec in recs %}
                                                        {% if rec.recommended_user == active_user and rec.parent_playlist_id == chosen_playlist.playlist_id %}
                                                            <ul class="rec-list">
                                                                <li>
                                                                    <div class="container song-thumb-container">
                                                                        <div class="row rec-row">

                                                                            <div class="col-sm-4">
                                                                                <div class="card rec-song-art">
                                                                                    <a href="https://open.spotify.com/track/{{ rec.song_id }}"
                                                                                       target="_blank">
                                                                                        <img class="img-responsive"
                                                                                             src="{{ rec.album_cover_art }}">
                                                                                    </a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-sm-8 button-div">
                                                                                <a target="_blank"
                                                                                   href="https://open.spotify.com/track/{{ rec.song_id }}">
                                                                                    <button type="button"
                                                                                            class="btn btn-success rec-song-button align-middle">
                                                                                        {{ rec.song_name }}
                                                                                        -
                                                                                        {{ rec.artist_name }}
                                                                                    </button>
                                                                                </a>
                                                                            </div>
                                                                </li>
                                                            </ul>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endif %}
                                                {% if no_recommendations %}
                                                    <div class="row">
                                                    <h4 class="no-rec-header">No recommendations! Try again</h4>
                                                    <div class="recommendation-text">
                                                        <p>It appears that either the playlist you selected did not
                                                            contain
                                                            any songs that match your criteria,
                                                            or your Spotify library is not very large. Please try again
                                                            with
                                                            a different playlist!</p>
                                                    </div>
                                                    <div class="col-xs-12 button-holder">
                                                    <div class="ajax-button">
                                                        <div class="fa fa-check done"></div>
                                                        <div class="fa fa-close failed"></div>
                                                        <a href="
                                        {% url "spotify_app:playlist_list" %}">
                                                            <input id="submit" class="submit rec-button" type="button"
                                                                   value="Back to Playlists"/></a>
                                                    </div>
                                                {% endif %}
                                            {% if Zero_liked_songs %}
                                                    <div class="row">
                                                    <h4 class="no-rec-header">No recommendations! Try again</h4>
                                                    <div class="recommendation-text">
                                                        <p>It appears that you haven't Liked any songs on your spotify account.
                                                            Please like a few songs to proceed further.</p>
                                                    </div>
                                                    <div class="col-xs-12 button-holder">
                                                    <div class="ajax-button">
                                                        <div class="fa fa-check done"></div>
                                                        <div class="fa fa-close failed"></div>
                                                        <a href="
                                        {% url "spotify_app:playlist_list" %}">
                                                            <input id="submit" class="submit rec-button" type="button"
                                                                   value="Back to Playlists"/></a>
                                                    </div>
                                                {% endif %}
                                                </div>
                                                </div>
                                                </div>
                                                <div class="container-fluid row ">
                                                    <div class="container">
                                                        <div class="row">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% else %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="jumbotron">
                        <h1 class="display-4">Spotify Song Recommender</h1>
                        <p class="lead">Please log in to your Spotify account to get song recommendations</p>
                        <p class="lead">
                            <a class="btn btn-success btn-lg" href="{% url "social:begin" "spotify" %}"
                               role="button">Log in with Spotify</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}